# Generated by Django 5.0 on 2026-06-28 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roseApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediccionmes',
            name='ganancia_maxima_2derivada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='prediccionmes',
            name='precio_optimo_1derivada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
